version: '3.8'

services:
  web:
    build: ./apache-php
    container_name: apache_php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword324311!!
      MYSQL_DATABASE: restaurantsProject
      MYSQL_USER: restaurantsUser
      MYSQL_PASSWORD: RestaurantsPassword324311!!
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword324311!!
    depends_on:
      - db

volumes:
  db_data:
