version: '3.8'

services:
  web:
    build: ./apache-php
    container_name: apache_php
    ports:
      - "9080:80"  # This is the internal port for Apache in Docker
    volumes:
      - ./src:/var/www/html
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
